# Generated by Django 5.1.7 on 2025-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("initials", models.CharField(max_length=3, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
    ]
